services:
  backend:
    build: ./backend
    env_file: .env.backend
    profiles:
      - prod
      - front_dev

  backend_dev:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    env_file: .env.backend
    profiles:
      - back_dev
    volumes:
      - ./backend/internal:/app/internal:ro
    networks:
      default:
        aliases:
          - backend

  frontend:
    build: ./frontend
    profiles:
      - prod
      - back_dev

  frontend_dev:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    profiles:
      - front_dev
    volumes:
      - ./frontend/src:/app/src:ro
      - /app/node_modules
    networks:
      default:
        aliases:
          - frontend

  nginx:
    build: ./nginx
    ports:
      - "80:80"

  redis:
    image: redis:7-alpine
