volumes:
  redis_data:
  postgres_data:

services:
  nginx:
    image: nginx:1.28.3-alpine
    ports: ["80:80", "443:443"]
    networks:
      default:
        aliases:
          - ${BASE_DOMAIN}
          - ${API_DOMAIN}
          - ${AUTH_DOMAIN}
          - ${ADMIN_DOMAIN}
    depends_on:
      swagger: { condition: service_started, required: false }
      backend: { condition: service_started, required: false }
      backend_dev: { condition: service_started, required: false }
      frontend: { condition: service_started, required: false }
      frontend_dev: { condition: service_started, required: false }
      auth: { condition: service_started }
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro"

  swagger:
    image: swaggerapi/swagger-ui:v5.32.1
    environment:
      SWAGGER_JSON_URL: /api/openapi.json

  backend:
    build: ./backend
    env_file: .env.backend
    depends_on: [redis]
    profiles: [prod, front_dev]

  backend_dev:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    env_file: .env.backend
    depends_on: [redis]
    profiles: [back_dev]
    volumes: ["./backend/internal:/app/internal:ro"]
    networks: { default: { aliases: [backend] } }

  redis:
    image: redis:7-alpine
    volumes: ["redis_data:/data"]

  frontend:
    build: ./frontend
    profiles: [prod, back_dev]
    env_file: .env.frontend.local
    environment:
      BASE_URL: "http://${BASE_DOMAIN}"
      OIDC_URL: "http://${AUTH_DOMAIN}"
      API_URL: "http://${API_DOMAIN}"

  frontend_dev:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    profiles: [front_dev]
    env_file: .env.frontend.local
    environment:
      BASE_URL: "http://${BASE_DOMAIN}"
      OIDC_URL: "http://${AUTH_DOMAIN}"
      API_URL: "http://${API_DOMAIN}"
    volumes: ["./frontend/src:/app/src:ro"]
    networks: { default: { aliases: [frontend] } }

  db:
    image: postgres:16-alpine
    healthcheck:
      test: pg_isready -U postgres
      timeout: 5s
      retries: 5
      interval: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      # API_DB_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro"

  auth:
    image: svhd/logto:latest
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    depends_on:
      redis: { condition: service_started }
      db: { condition: service_healthy }
    environment:
      TRUST_PROXY_HEADER: "1"
      DB_URL: postgres://logto:${AUTH_DB_PASSWORD}@db:5432/logto
      REDIS_URL: redis://redis:6379
      ENDPOINT: http://${AUTH_DOMAIN}
      ADMIN_ENDPOINT: http://${ADMIN_DOMAIN}
