services:
  nginx:
    build: ./nginx
    ports: ["80:80"]
    depends_on:
      swagger:
        condition: service_started
        required: false
      backend:
        condition: service_started
        required: false
      backend_dev:
        condition: service_started
        required: false
      frontend:
        condition: service_started
        required: false
      frontend_dev:
        condition: service_started
        required: false

  swagger:
    image: swaggerapi/swagger-ui:v5.18.2
    environment:
      SWAGGER_JSON_URL: /api/openapi.json

  backend:
    build: ./backend
    env_file: .env.backend
    depends_on: [redis]
    profiles: [prod, front_dev]

  backend_dev:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    env_file: .env.backend
    depends_on: [redis]
    profiles: [back_dev]
    volumes: ["./backend/internal:/app/internal:ro"]
    networks:
      default:
        aliases:
          - backend

  redis:
    image: redis:7-alpine

  frontend:
    build: ./frontend
    profiles: [prod, back_dev]

  frontend_dev:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    profiles: [front_dev]
    volumes: ["./frontend/src:/app/src:ro"]
    networks:
      default:
        aliases:
          - frontend
