root = "."
tmp_dir = "tmp"

[build]
  cmd = "./refresh.sh"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "docs"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true

[log]
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
