FROM golang:1.26.1-alpine

RUN apk add --no-cache gcc musl-dev git

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN chmod +x refresh.sh && ./refresh.sh

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
