FROM golang:1.26-alpine

RUN apk add --no-cache gcc musl-dev git

WORKDIR /app

ENV GIN_MODE=debug

RUN go install github.com/air-verse/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN chmod +x refresh.sh && \
    ./refresh.sh

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "./healthcheck.sh" ]
CMD ["air", "-c", ".air.toml"]
